import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {initialWorld,gradeArgument,type StudentState,type Turn} from '../lib/world';
import {ArgumentSchema,materials,passages,sourceVersion,validateCitations,revisionStatus,previousSubmission,preserveReviewedSources,type Citation} from '../lib/learning';
import {replaceWorldSql,saveStudentSql} from '../lib/classroomWrites';
import {directorContext} from '../lib/directorContext';
import {boundedJson} from '../lib/requestBody';
import {alexandriaHintPositions,generatedHintPositions,visibleAtActivity} from '../components/worlds/scene/lessonEffects';

const student=():StudentState=>({name:'B',evidence:['strabo','funding','ledger'],turns:[],zone:'library',unlocked:false});
async function citation(id='strabo'):Promise<Citation>{const e=initialWorld.evidence.find(e=>e.id===id)!,m=materials(e)[0],p=passages(m.text)[0];return {evidenceId:id,material:m.id,sourceVersion:await sourceVersion(e),...p,relevance:'This supports institutional support, but not an exclusive source of income.'};}
test('new contextual sources cite their exact excerpt while legacy paraphrases keep the verified short quotation',async()=>{
 const current=initialWorld.evidence[0],c=await citation();assert.equal(c.material,'text');assert.equal(materials(current).length,1);assert.equal(materials(current)[0].text,current.text);assert.deepEqual(await validateCitations([c],student(),initialWorld),[c]);
 const legacy={...current,context:undefined,source:'Strabo, Geography 17.1.8 · https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Strabo/17A1*.html',text:'Strabo describes a shared dining hall and a learned community at the Museum, within the royal palaces. This supports an institutional context; it does not establish trade as its only source of funding.'};
 assert.equal(materials(legacy)[0].id,'excerpt');assert.equal(materials(legacy)[1].label,'Reading note · paraphrase');
 const oldFields=JSON.stringify([legacy.id,legacy.title,legacy.text,legacy.kind,legacy.source,legacy.zone,materials(legacy)]);
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(oldFields))),b=>b.toString(16).padStart(2,'0')).join('');assert.equal(await sourceVersion(legacy),hash);
});
test('context and editorial provenance changes invalidate citations and cannot replace reviewed sources',async()=>{
 const e=initialWorld.evidence[0],v=await sourceVersion(e),c=await citation();
 for(const field of ['text','locator','sourceVersion','start','end','editorialNote','readingNote','references'] as const){
  const w=structuredClone(initialWorld),context=w.evidence[0].context!;
  Object.assign(context,{[field]:field==='start'||field==='end'?context[field]+1:field==='references'?[{title:'Changed',url:'https://example.org/changed'}]:String(context[field]??'')+' changed'});
  assert.notEqual(await sourceVersion(w.evidence[0]),v);await assert.rejects(validateCitations([c],student(),w));assert.throws(()=>preserveReviewedSources(w,initialWorld));
 }
});
test('quotation forgery, unavailable material, stale version and duplicate citation reject',async()=>{const c=await citation();for(const forged of [{...c,quote:'invented quote'},{...c,start:1},{...c,end:9000},{...c,sourceVersion:'0'.repeat(64)},{...c,evidenceId:'unknown'},{...c,material:'other'}])await assert.rejects(validateCitations([forged],student(),initialWorld));await assert.rejects(validateCitations([c,c],student(),initialWorld));await assert.rejects(validateCitations([c],{...student(),evidence:[]},initialWorld));});
test('source version tracks content and provenance but not hints or scenario state',async()=>{const e=initialWorld.evidence[0],v=await sourceVersion(e);assert.equal(v,await sourceVersion({...e}));for(const field of ['text','source','title'] as const)assert.notEqual(v,await sourceVersion({...e,[field]:e[field]+' changed'}));});
test('sentence selection uses exact UTF-16 offsets including emoji and whitespace',()=>{const text='  An 🦉 watches.\nA second view challenges it! What follows?';for(const p of passages(text))assert.equal(text.slice(p.start,p.end),p.quote);assert.equal(passages(text).length,3);});
test('every reviewed source must remain present and unchanged, without invented replacements',()=>{for(const field of ['id','title','text','kind','source','zone'] as const){const w=structuredClone(initialWorld);Object.assign(w.evidence[0],{[field]:'changed'});assert.throws(()=>preserveReviewedSources(w,initialWorld));}const w=structuredClone(initialWorld);w.evidence.shift();assert.throws(()=>preserveReviewedSources(w,initialWorld));const invented=structuredClone(initialWorld);invented.evidence.push({...initialWorld.evidence[0],id:'fake'});assert.throws(()=>preserveReviewedSources(invented,initialWorld));const valid=structuredClone(initialWorld);valid.evidence[1].text='A different explicitly invented comparison.';assert.equal(preserveReviewedSources(valid,initialWorld),valid);});
test('unchanged answers, case, whitespace and punctuation cannot establish a revision',()=>{const s=student();s.turns=[{claim:'A patron could help.'} as Turn];const input=ArgumentSchema.parse({requestId:crypto.randomUUID(),claim:' A PATRON could help!!! ',npc:'library',scenario:false,citations:[],revisesTurnId:'legacy-0',reflection:'I reconsidered the original conclusion.'});assert.equal(revisionStatus(input,s),false);assert.equal(revisionStatus({...input,claim:'A patron could help, conditional on continued support.'},s),true);assert.throws(()=>revisionStatus({...input,reflection:''},s));assert.throws(()=>revisionStatus({...input,revisesTurnId:'foreign'},s));});
test('retry IDs replay identical submissions and reject changed payloads',()=>{const input=ArgumentSchema.parse({requestId:crypto.randomUUID(),claim:'A patron could help.',npc:'library',scenario:false,citations:[]}),turn={id:input.requestId,claim:input.claim,submission:JSON.stringify(input)} as Turn,s=student();s.turns=[turn];assert.equal(previousSubmission(input,s),turn);assert.throws(()=>previousSubmission({...input,claim:'Different claim'},s));});
test('all four dimensions including uncertainty are needed for new archive milestones',()=>{const claim='A patron could help.',r={reply:'Consider the uncertainty.',items:['claim','evidence','mechanism','limitation'].map(key=>({key,earned:key!=='limitation',excerpt:claim,reason:'Supported'})),evidenceIds:['funding'],nextQuestion:'What would change your conclusion?'};assert.equal(gradeArgument(r,claim,['funding'],initialWorld).unlocked,false);r.items[3].earned=true;assert.equal(gradeArgument(r,claim,['funding'],initialWorld).unlocked,true);assert.throws(()=>gradeArgument(r,claim,[],initialWorld));});
for(const field of ['prediction','archiveReflection'])for(const progressFirst of [true,false])test(`atomic ${field}/replacement race, progress first=${progressFirst}`,()=>{const db=new DatabaseSync(':memory:');try{db.exec('CREATE TABLE classrooms(id TEXT PRIMARY KEY,state TEXT,world TEXT,lesson TEXT,version INTEGER); CREATE TABLE students(id TEXT PRIMARY KEY,class_id TEXT,state TEXT,revision INTEGER);');db.prepare('INSERT INTO classrooms VALUES (?,?,?,?,?)').run('c','{}','old','lesson',1);db.prepare('INSERT INTO students VALUES (?,?,?,?)').run('s','c',JSON.stringify(student()),1);const state=JSON.stringify({...student(),evidence:[],[field]:{text:'Original thinking'}});db.prepare('UPDATE students SET state=?').run(JSON.stringify({...student(),evidence:[]}));const save=()=>db.prepare(saveStudentSql).run(state,'s',1,1).changes,replace=()=>db.prepare(replaceWorldSql).run('{}','new','lesson','c',1).changes;assert.equal(progressFirst?save():replace(),1);assert.equal(progressFirst?replace():save(),0);}finally{db.close();}});
test('director resolves selected same-class stored state and rejects missing/foreign/unauthorized identities',async()=>{const id=crypto.randomUUID(),b=crypto.randomUUID(),s={...student(),turns:[{claim:'B thinks a patron could help.'}]};const database={prepare:(sql:string)=>({bind:(...args:unknown[])=>({first:async()=>sql.includes('teacher_token')?args[0]===id?{teacher_token:'teacher'}:null:args[0]===b&&args[1]===id?{id:b,state:JSON.stringify(s),revision:7}:null})})} as unknown as D1Database;assert.deepEqual(await directorContext(database,id,'teacher',b),{student:s,basis:{studentId:b,name:'B',revision:7}});for(const learner of [undefined,'not-an-id',crypto.randomUUID()])await assert.rejects(directorContext(database,id,'teacher',learner));await assert.rejects(directorContext(database,id,'student-token',b));});
test('actual streamed body limit works without Content-Length, including multibyte input',async()=>{for(const text of ['x'.repeat(31),'🦉'.repeat(8)])await assert.rejects(boundedJson(new Request('https://test',{method:'POST',body:text}),30),/large/);assert.deepEqual(await boundedJson(new Request('https://test',{method:'POST',body:'{"action":"create"}'})),{action:'create'});});
test('zone activity is isolated and every scene has distinct hint anchors',()=>{for(const changed of ['harbor','market','library'] as const){const w=structuredClone(initialWorld);w.nodes.forEach(n=>n.activity=n.id===changed?0:1);for(const zone of ['harbor','market','library'] as const){assert.equal(visibleAtActivity(w,zone,0,10,1),zone!==changed);assert.equal(visibleAtActivity(w,zone,9,10,0),true);}}for(const positions of [alexandriaHintPositions,generatedHintPositions])assert.equal(new Set(Object.values(positions).map(p=>JSON.stringify(p))).size,3);});

test('drafts restore without erasing saved content and remain isolated by learner and source',async()=>{const {createDraftStore}=await import('../lib/draftStore');const data=new Map<string,string>(),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};const first=createDraftStore('class:B','source1',()=>storage);first.subscribe(()=>{});first.update(d=>({...d,claim:'Original draft',prediction:'A patron might help',pending:{id:'retry-id',content:'exact request'}}));const restored=createDraftStore('class:B','source1',()=>storage);restored.subscribe(()=>{});assert.equal(restored.read().claim,'Original draft');assert.equal(restored.read().pending?.id,'retry-id');const other=createDraftStore('class:A','source1',()=>storage);other.subscribe(()=>{});assert.equal(other.read().claim,'');const changed=createDraftStore('class:B','source2',()=>storage);changed.subscribe(()=>{});assert.equal(changed.read().claim,'');restored.update(d=>({...d,claim:'Newer typing'}));restored.update(d=>d.claim==='Original draft'?{...d,claim:''}:d);assert.equal(restored.read().claim,'Newer typing');});
test('storage failure leaves an editable in-memory draft and visible recovery warning',async()=>{const {createDraftStore}=await import('../lib/draftStore');const store=createDraftStore('B','v1',()=>{throw new Error('storage blocked');});store.subscribe(()=>{});store.update(d=>({...d,claim:'Still here'}));assert.equal(store.read().claim,'Still here');assert.match(store.getSnapshot().warning,/could not be saved/);});
