import {test} from 'node:test';
import assert from 'node:assert/strict';
import {groundLesson,textPassages,publicPdfUrl} from '../lib/lessonBuilder';
import {initialWorld} from '../lib/world';
const source='Ada believed the bridge belonged to everyone. Her neighbour argued that the builder should charge a toll. At the town meeting, a child asked who would carry medicine across the river if the toll was too high. The council paused the vote to hear from the ferryman. He described the winter floods but offered no price for a crossing.';
const passages=textPassages(source);
const pack={subject:'literature',scene:'garden',sourceTitle:'Untrusted replacement',readingRange:'wrong range',characters:initialWorld.nodes.map(n=>({zone:n.id,name:'Guide',role:'Fictional guide',perspective:'Ask about evidence',starters:['Why?','What supports it?']})),activities:initialWorld.nodes.map(n=>({zone:n.id,instruction:'Compare perspectives.'}))};
function generated(){return {...structuredClone(initialWorld),lessonPack:structuredClone(pack),nodes:initialWorld.nodes.map((n,i)=>({...n,evidenceIds:[passages[i].id]})),evidence:initialWorld.evidence.map((e,i)=>({...e,id:passages[i].id,kind:'source',zone:initialWorld.nodes[i].id,text:'Invented text the model supplied',source:'Invented citation'}))};}
test('text passages retain exact source substrings and valid locators',()=>{assert.equal(passages.length,3);for(const p of passages){assert.ok(source.includes(p.text));assert.ok(p.text.length<=700);assert.match(p.locator,/Characters/);}const long=textPassages(source.repeat(100));assert.ok(long.every(p=>source.repeat(100).includes(p.text)&&p.text.length<=700));});
test('source sizes and private/non-PDF links are rejected',()=>{assert.throws(()=>textPassages('too short'));assert.throws(()=>textPassages('x'.repeat(60001)));for(const url of ['http://example.com/x.pdf','https://127.0.0.1/x.pdf','https://localhost/x.pdf','https://a.internal/x.pdf','https://user:pass@example.com/x.pdf','https://example.com/page','https://example.com:8443/a.pdf'])assert.throws(()=>publicPdfUrl(url));assert.equal(publicPdfUrl('https://example.com/chapter.pdf'),'https://example.com/chapter.pdf');});
test('canonical text and citations replace model-authored source claims',()=>{const w=groundLesson(generated(),passages,'The bridge','Chapter 1');assert.equal(w.evidence[0].text,passages[0].text);assert.equal(w.evidence[0].source,`The bridge · ${passages[0].locator}`);assert.equal(w.lessonPack?.sourceTitle,'The bridge');assert.equal(w.lessonPack?.readingRange,'Chapter 1');});
test('invented IDs, source kinds, and duplicate character locations fail closed',()=>{let w=generated();w.evidence[0].id='made-up';assert.throws(()=>groundLesson(w,passages,'Bridge',''));w=generated();w.evidence[0].kind='assumption';assert.throws(()=>groundLesson(w,passages,'Bridge',''));w=generated();w.lessonPack.characters[1].zone=w.lessonPack.characters[0].zone;assert.throws(()=>groundLesson(w,passages,'Bridge',''));});

test('each source station requires a local linked card',()=>{const w=generated();w.evidence.forEach(e=>e.zone='harbor');assert.throws(()=>groundLesson(w,passages,'Bridge',''));});
