'use client';
import {useEffect,useMemo,useState} from 'react';
import PageHeader from '@/components/PageHeader';
import ModelPreview from './ModelPreview';
import {catalogSize,catalogLabel} from '@/lib/modelCatalog';
import {characterUses,characterSetupCode,verifyCharacterCatalog,type CharacterCatalogAsset} from '@/lib/characterCatalog';
import './model-catalog.css';

function CharacterDetail({asset,scene}:{asset:CharacterCatalogAsset;scene:string}){
 const uses=asset.assignments.filter(u=>scene==='all'||u.worldId===scene),[selectedUse,setSelectedUse]=useState(''),[copied,setCopied]=useState('');
 const use=uses.find(u=>`${u.worldId}:${u.zone}`===selectedUse)??uses[0],code=characterSetupCode(use.worldId);
 return <article id="selected-character" className="model-detail">
  <div className="model-detail-heading"><div><span className="model-kicker">Original teaching character · {catalogLabel(asset.family)}</span><h2>{asset.title}</h2><code className="model-id">{asset.id}</code></div><div className="model-actions"><a className="model-download" href={asset.url} download>Download GLB · {catalogSize(asset.bytes)}</a><a href={`/model-catalog?collection=characters&asset=${encodeURIComponent(asset.id)}&scene=${encodeURIComponent(use.worldId)}`}>Link to this character</a></div></div>
  <div className="model-workspace"><div><ModelPreview asset={asset}/><dl className="model-metrics"><div><dt>Triangles</dt><dd>{asset.triangles.toLocaleString()}</dd></div><div><dt>Materials / skins</dt><dd>{asset.materials} / {asset.skins}</dd></div><div><dt>Source dimensions · X / Y / Z</dt><dd>{asset.dimensions.map(n=>n.toFixed(2)).join(' / ')} m</dd></div><div><dt>Animation clips</dt><dd>{asset.clips.join(', ')}</dd></div></dl></div>
   <section className="model-integrate" aria-label="Character integration instructions"><span className="model-readiness ready">Assigned to lesson scenes</span><h3>Reuse the scene’s cast</h3><label>Scene and role<select value={`${use.worldId}:${use.zone}`} onChange={e=>{setSelectedUse(e.target.value);setCopied('');}}>{uses.map(u=><option key={`${u.worldId}:${u.zone}`} value={`${u.worldId}:${u.zone}`}>{u.worldLabel} · {u.role}</option>)}</select></label><a href={`/worlds?lesson=${encodeURIComponent(use.worldId)}-01`}>Explore this lesson scene →</a><div className="model-copy"><button onClick={async()=>{try{await navigator.clipboard.writeText(code);setCopied('Copied');}catch{setCopied('Select the code below to copy it.');}}}>Copy cast setup</button><span role="status">{copied}</span></div><textarea className="model-code" readOnly spellCheck={false} aria-label="Character setup code" value={code} onFocus={e=>e.currentTarget.select()}/><p className="model-help">The example attaches the complete three-person cast to positioned fallback groups. Existing lesson renderers already do this. Keep their update, talk, reduced-motion and cleanup hooks.</p><p className="model-help">Change reviewed assignments in <code>characterCostumes.ts</code>. Each instance must own its skeleton; the static prop loader is not suitable for these characters.</p></section>
  </div>
  <section className="model-guidance"><h3>{use.period}</h3><p>{use.interpretation}</p><p className="model-caution">All companions are fictional readers. Clothing is interpreted, and does not authenticate a person or event in the source.</p><p className="model-help">The preview shows source proportions. Lesson loaders ground, center and scale the character for its scene. Motion previews run only after you press Play.</p>{use.references.map(r=><p key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.title}</a></p>)}</section>
  <details className="model-section"><summary>All scene assignments <span>{asset.assignments.length}</span></summary><div className="model-table-wrap"><table><thead><tr><th>World</th><th>Reading role</th><th>Clothing context</th></tr></thead><tbody>{asset.assignments.map(u=><tr key={`${u.worldId}:${u.zone}`}><td><a href={`/worlds?lesson=${u.worldId}-01`}>{u.worldLabel}</a></td><td>{u.role}<code>{u.zone}</code></td><td>{u.period}</td></tr>)}</tbody></table></div></details>
  <details className="model-section"><summary>Editable source, license and file identity</summary><p>Creator: {asset.creator}. <a href={asset.licenseUrl}>MIT license notice</a> — retain the copyright and permission notice when redistributing copies.</p><p>Editable source: <code>{asset.sourcePath}</code></p><p>Anchors: {asset.anchors.join(', ')}.</p><p>SHA-256</p><code className="model-hash">{asset.sha256}</code></details>
 </article>;
}

export default function CharacterCatalog({initialAssetId='',initialScene='all'}:{initialAssetId?:string;initialScene?:string}){
 const scenes=[...new Map(characterUses.map(u=>[u.worldId,u.worldLabel])).entries()];
 const [assets,setAssets]=useState<CharacterCatalogAsset[]>([]),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[search,setSearch]=useState(''),[scene,setScene]=useState(scenes.some(([id])=>id===initialScene)?initialScene:'all'),[family,setFamily]=useState('all'),[selected,setSelected]=useState(initialAssetId);
 useEffect(()=>{const abort=new AbortController();fetch('/models/characters/catalog.json',{cache:'no-store',signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The character catalog could not load.');return r.json();}).then(data=>{if(!abort.signal.aborted)setAssets(verifyCharacterCatalog(data));}).catch(e=>{if(!abort.signal.aborted){setAssets([]);setError(`${e.message} Retry, or reload after an app update.`);}});return()=>abort.abort();},[attempt]);
 const filtered=useMemo(()=>assets.filter(a=>(scene==='all'||a.assignments.some(u=>u.worldId===scene))&&(family==='all'||a.family===family)&&`${a.title} ${a.id} ${a.assignments.map(u=>u.period).join(' ')}`.toLowerCase().includes(search.toLowerCase().trim())),[assets,scene,family,search]);
 const asset=filtered.find(a=>a.id===selected)??filtered[0];
 useEffect(()=>{if(!asset)return;const url=new URL(window.location.href);url.searchParams.set('asset',asset.id);if(scene==='all')url.searchParams.delete('scene');else url.searchParams.set('scene',scene);window.history.replaceState(window.history.state,'',url);},[asset,scene]);
 function reset(){setSearch('');setScene('all');setFamily('all');}
 function select(id:string){setSelected(id);if(window.matchMedia('(max-width: 760px)').matches)requestAnimationFrame(()=>document.getElementById('selected-character')?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));}
 return <main className="model-catalog"><PageHeader/><header className="model-catalog-header"><div><span className="model-kicker">COUNTERFACTUAL WORLDS · DEVELOPMENT LIBRARY</span><h1>Teaching characters</h1><p>Preview a reader, check its scene assignment, and reuse the existing cast loader.</p></div><nav aria-label="Catalog resources"><a href="/model-catalog">Props & references</a><a href="/models/characters/catalog.json" download>Export character catalog</a></nav></header>
  <div className="model-status-bar" aria-live="polite">{assets.length?<><strong>{assets.length} registered characters</strong><span>{characterUses.length} role assignments · {scenes.length} worlds</span><span>Each lesson uses three readers</span></>:<span>{error?'Character catalog needs attention':'Loading character records…'}</span>}</div>
  {error&&<div role="alert" className="model-error"><p>{error}</p><button onClick={()=>{setError('');setAttempt(n=>n+1);}}>Retry catalog</button></div>}
  <div className="model-catalog-body"><aside className="model-library" aria-label="Find teaching characters"><label htmlFor="character-search">Search characters</label><input id="character-search" type="search" placeholder="Name, clothing, period…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="model-filters"><label>Lesson scene<select value={scene} onChange={e=>setScene(e.target.value)}><option value="all">All scenes</option>{scenes.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><label>Collection<select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All collections</option>{[...new Set(assets.map(a=>a.family))].map(f=><option key={f} value={f}>{catalogLabel(f)}</option>)}</select></label></div><div className="model-results"><span aria-live="polite">{filtered.length} results</span><button onClick={reset}>Clear filters</button></div><div className="model-list">{filtered.map(a=><button key={a.id} className={a.id===asset?.id?'selected':''} aria-pressed={a.id===asset?.id} onClick={()=>select(a.id)}><strong>{a.title}</strong><span>{catalogSize(a.bytes)} · {a.assignments.length} assignments</span><small>{catalogLabel(a.family)}</small></button>)}</div></aside>
   {asset&&<CharacterDetail key={`${asset.id}:${scene}`} asset={asset} scene={scene}/>}{!asset&&assets.length>0&&<section className="model-empty"><h2>No matching characters</h2><p>Clear the filters to browse all assigned readers.</p><button onClick={reset}>Show all characters</button></section>}
  </div>
 </main>;
}
