import {museumCitation} from './museums';
import {getMuseumInvestigation,investigationObjects} from './museumInvestigations';
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function museumWorksheetHtml(id:string){
 const plan=getMuseumInvestigation(id);
 if(!plan)throw new Error('Choose a reviewed museum investigation.');
 const items=investigationObjects(plan);
 if(items.length!==2)throw new Error('This investigation needs two reviewed objects.');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${escape(plan.title)} — museum worksheet</title><style>
 body{max-width:800px;margin:40px auto;padding:0 24px;color:#171717;font:15px/1.6 system-ui,sans-serif}h1,h2,h3{line-height:1.2}h1{font-size:32px;letter-spacing:-.03em}h2{font-size:23px;margin-top:30px}h3{font-size:18px}p,li,small{overflow-wrap:anywhere}small{font-size:12px}.eyebrow{font-size:11px;letter-spacing:.1em}article{border-top:2px solid #171717;padding-top:12px;margin-top:24px}dl{display:grid;grid-template-columns:90px 1fr;gap:6px;font-size:13px}dd{margin:0}.answer{height:100px;border-bottom:1px solid #888}.source{font-size:12px}.record{break-before:page}.reading{border-left:2px solid #d8321c;padding-left:14px;margin-top:30px}.screen{background:#f3f3f1;padding:12px}a{color:inherit}footer{font-size:12px;border-top:1px solid #aaa;margin-top:24px;padding-top:12px}@media print{body{margin:0;padding:0;font-size:12px}.screen{display:none}h2,h3{break-after:avoid}article{break-inside:avoid}.answer{height:80px}@page{margin:18mm}}
 </style></head><body><p class="eyebrow">COUNTERFACTUAL WORLDS / OBJECT INVESTIGATION</p><h1>${escape(plan.title)}</h1><p>${escape(plan.topic)} · ${plan.minutes} minutes · two museum objects</p><p>Name: ____________________________ &nbsp; Date: ______________</p><p class="screen">Open this file in a browser and choose Print to print it or save a PDF. The questions and records work offline. Before disconnecting, open the linked museum photographs or ask your teacher to project them; photographs are not embedded in this worksheet.</p><p>${escape(plan.summary)}</p><p>Objects: ${items.map(item=>`${escape(item.title)} (${escape(item.accession)})`).join(' and ')}.</p>
 ${plan.steps.map((step,index)=>`<article><h2>${index+1}. ${escape(step.title)} <small>· ${step.minutes} min</small></h2><p>${escape(step.prompt)}</p><div class="answer" aria-label="Space for your response"></div></article>`).join('')}
 <section class="reading"><h3>Return to the reading</h3><p>${escape(plan.readingBridge)}</p></section>
 <section class="record"><h2>The museum records</h2><p>Photographs may be fitted at different sizes. Use recorded dimensions, when available, to compare physical scale.</p>${items.map(item=>`<article><h3>${escape(item.title)}</h3><dl><dt>Date</dt><dd>${escape(item.date)}</dd><dt>Material</dt><dd>${escape(item.medium)}</dd><dt>Culture / place</dt><dd>${escape(item.culture)}</dd><dt>Dimensions</dt><dd>${escape(item.dimensions)}</dd><dt>Maker</dt><dd>${escape(item.creator)}</dd></dl><p><strong>What this object cannot establish</strong><br>${escape(item.limits)}</p><p class="source">${escape(museumCitation(item))}</p><p><a href="${escape(item.recordUrl)}">Original museum record</a> · <a href="${escape(item.imageUrl)}">Museum photograph (online)</a> · <a href="${escape(item.licenseUrl)}">CC0</a></p></article>`).join('')}</section><footer>Questions written for Counterfactual Worlds, not museum quotations. This is contextual discussion, separate from source-card assessment. No museum partnership is implied.</footer></body></html>`;
}
