'use client';
import type {StudentState,World} from '@/lib/world';
import {turnId} from '@/lib/learning';
import type {LearningDraft} from './useLearningDraft';

type Props={student:StudentState;world:World;draft:LearningDraft;busy:boolean;update:(change:(d:LearningDraft)=>LearningDraft)=>void;onPredict:()=>void;onSubmit:()=>void;onReflect:()=>void;onEvidence:(id:string)=>void};
export default function LearningWork({student,world,draft,busy,update,onPredict,onSubmit,onReflect,onEvidence}:Props){
 const revision=student.turns.find((t,i)=>turnId(t,i)===draft.revisesTurnId);
 return <div className="learning-work">
  {!student.prediction&&!student.turns.length?<section className="prediction-card"><label htmlFor="prediction">Your starting prediction</label><p className="helper">What do you think, before making your case? You can change your mind later.</p><textarea id="prediction" value={draft.prediction} maxLength={600} onChange={e=>update(d=>({...d,prediction:e.target.value}))}/><button className="primary-button small" disabled={busy||draft.prediction.trim().length<3} onClick={onPredict}>Save starting prediction</button></section>:<details><summary>Starting prediction</summary><p>{student.prediction?.text??'No initial prediction was recorded for this earlier work.'}</p></details>}
  <div className="claim-compose"><label htmlFor="claim">{revision?'Revise your explanation':'Make your argument'}</label>
   {revision&&<div className="revision-context"><strong>Earlier explanation</strong><blockquote>{revision.claim}</blockquote><p>Feedback: {revision.result.nextQuestion}</p><button className="quiet-button" onClick={()=>update(d=>({...d,revisesTurnId:undefined,reflection:''}))}>Cancel revision</button></div>}
   <textarea id="claim" placeholder="I think… because the selected passage shows…" value={draft.claim} onChange={e=>update(d=>({...d,claim:e.target.value}))} maxLength={1600}/>
   <p className="helper">Choose a passage in the reader and explain how it supports your argument. Saved journal items are not automatically cited.</p>
   <div className="collected-tags">{world.evidence.filter(e=>student.evidence.includes(e.id)).map(e=><button key={e.id} onClick={()=>onEvidence(e.id)}>{e.title}</button>)}</div>
   <div className="selected-citations">{draft.citations.map((c,i)=><article key={`${c.evidenceId}:${c.material}:${c.start}`}><button className="text-button" onClick={()=>onEvidence(c.evidenceId)}>{world.evidence.find(e=>e.id===c.evidenceId)?.title} · {c.material==='excerpt'?'Source excerpt':'Selected material'}</button><blockquote>{c.quote}</blockquote><p>{c.relevance}</p><button className="quiet-button" aria-label={`Remove citation ${i+1}`} onClick={()=>update(d=>({...d,citations:d.citations.filter((_,n)=>n!==i)}))}>Remove</button></article>)}</div>
   {revision&&<><label htmlFor="revision-reflection">What changed in your reasoning, and why?</label><textarea id="revision-reflection" value={draft.reflection} maxLength={600} onChange={e=>update(d=>({...d,reflection:e.target.value}))}/></>}
   <button className="primary-button" disabled={busy||draft.claim.trim().length<3||(!student.prediction&&!student.turns.length)||!!revision&&draft.reflection.trim().length<10} onClick={onSubmit}>{busy?'Please wait…':revision?'Submit revision':'Defend your idea'}</button>
   <p className="helper">Astra feedback is provisional. You can disagree with the hypothesis. A submitted revision is not a measured learning gain.</p>
   {student.turns.length>0&&!revision&&<div className="revision-choices"><label htmlFor="revise-choice">Choose an earlier explanation to revise</label><select id="revise-choice" value="" onChange={e=>{const t=student.turns.find((turn,i)=>turnId(turn,i)===e.target.value);if(t)update(d=>({...d,claim:t.claim,citations:t.citations??[],revisesTurnId:e.target.value,reflection:''}));}}><option value="">Select an explanation…</option>{student.turns.map((t,i)=><option key={turnId(t,i)} value={turnId(t,i)}>Explanation {i+1}: {t.claim.slice(0,60)}</option>)}</select></div>}
  </div>
  {student.unlocked&&<section className="archive-activity" id="archive-activity"><h3>Archive reflection available</h3><p>This is an argument milestone. The reflection is available here; the building interior is not part of this lesson.</p><p>{world.lessonPack?.subject==='literature'?'Use a selected passage to support another plausible reading. Which detail makes your first interpretation less certain?':'Reopen the funding assumption or another source. What alternative could change your conclusion, and what evidence would distinguish it?'}</p><div className="collected-tags">{world.evidence.map(e=><button key={e.id} onClick={()=>onEvidence(e.id)}>{e.title}</button>)}</div>{student.archiveReflection&&<blockquote>Saved reflection: {student.archiveReflection.text}</blockquote>}<label htmlFor="archive-reflection">Compare another explanation</label><textarea id="archive-reflection" value={draft.archive} maxLength={600} onChange={e=>update(d=>({...d,archive:e.target.value}))}/><button className="primary-button small" disabled={busy||draft.archive.trim().length<10} onClick={onReflect}>Save archive reflection</button></section>}
 </div>;
}
