'use client';
import {useEffect,useState} from 'react';
import {Sparkles,BookOpen,Check,LoaderCircle,Upload,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {BuilderAccess,LessonDraft} from '@/lib/lessonBuilder';
type Props={open:boolean;onClose:()=>void;ensure:()=>Promise<BuilderAccess>;onLaunch:(access:BuilderAccess)=>void};
export default function LessonBuilder({open,onClose,ensure,onLaunch}:Props){
 const [mode,setMode]=useState('text'),[title,setTitle]=useState(''),[range,setRange]=useState(''),[objective,setObjective]=useState(''),[text,setText]=useState(''),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[draft,setDraft]=useState<LessonDraft|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[reviewed,setReviewed]=useState(false),[access,setAccess]=useState<BuilderAccess|null>(null),[original,setOriginal]=useState<{draftId:string;url:string}|null>(null);
 useEffect(()=>{if(!open)return;let active=true;setBusy('Restoring your lesson draft…');setAccess(null);setDraft(null);setReviewed(false);setError('');ensure().then(async c=>{if(!active)return;setAccess(c);const r=await fetch(`/api/lesson-builder?id=${c.id}`,{headers:{Authorization:`Bearer ${c.teacherToken}`}});if(!r.ok)throw new Error('Could not restore lesson draft.');const data=await r.json() as {draft:LessonDraft|null};if(active)setDraft(data.draft);}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy('');});return()=>{active=false;};},[open]);
 useEffect(()=>{setOriginal(null);setReviewed(false);},[draft?.id]);
 useEffect(()=>()=>{if(original)URL.revokeObjectURL(original.url);},[original]);
 async function request<T>(body:FormData|Record<string,unknown>){const c=access??await ensure();setAccess(c);const r=await fetch(`/api/lesson-builder?id=${c.id}`,{method:'POST',headers:{Authorization:`Bearer ${c.teacherToken}`,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body instanceof FormData?body:JSON.stringify(body)});const data=await r.json() as T&{error?:string};if(!r.ok)throw new Error(data.error||'Could not build the lesson. Please retry.');return data;}
 async function build(existing?:LessonDraft){setError('');setReviewed(false);try{let d=existing;if(!d){setBusy('Reading your source material…');const form=new FormData();form.set('title',title);form.set('range',range);form.set('objective',objective);if(mode==='file'&&file)form.set('file',file);else form.set(mode==='url'?'url':'text',mode==='url'?url:text);d=await request<LessonDraft>(form);setDraft(d);}setBusy('Designing places, characters, evidence, and activities…');setDraft(await request<LessonDraft>({action:'generate',draftId:d.id}));}catch(e){setError(e instanceof Error?e.message:'Build failed.');}finally{setBusy('');}}
 async function launch(){if(!draft)return;setBusy('Opening your new classroom…');setError('');try{const c=await request<BuilderAccess>({action:'launch',draftId:draft.id,reviewed});onLaunch(c);setDraft(null);setReviewed(false);onClose();}catch(e){setError(e instanceof Error?e.message:'Launch failed.');}finally{setBusy('');}}
 async function viewOriginal(){if(!draft||!access)return;setError('');try{const r=await fetch(`/api/lesson-builder?id=${access.id}&draftId=${draft.id}&source=1`,{headers:{Authorization:`Bearer ${access.teacherToken}`}});if(!r.ok)throw new Error('Original upload unavailable. For linked PDFs, compare with the PDF at the address you supplied.');setOriginal({draftId:draft.id,url:URL.createObjectURL(await r.blob())});}catch(e){setError(e instanceof Error?e.message:'Unable to open source');}}
 const ready=!!draft?.world;
 return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="lesson-builder"><header><span className="eyebrow">FROM THE PAGE INTO THE WORLD</span><DialogTitle>{ready?'Your lesson is ready to review.':'Give Astra the material. It builds the lesson.'}</DialogTitle><DialogDescription>Textbook chapters, literary passages, and your own teaching notes become an explorable, evidence-led lesson.</DialogDescription><ol className="builder-steps"><li className={!draft?'active':''}>1 · Source</li><li className={draft&&!ready?'active':''}>2 · Astra builds</li><li className={ready?'active':''}>3 · Review & launch</li></ol></header><div className="builder-body">
 {error&&<p role="alert" className="character-error">{error}</p>}
 {busy&&<div className="builder-progress" role="status"><LoaderCircle className="spin"/><strong>{busy}</strong><p>You can leave the source selection to Astra. Each model step can take up to two minutes.</p></div>}
 {!draft&&!busy&&<><div className="builder-modes" role="group" aria-label="Source type">{[['text','Paste text'],['file','Upload file'],['url','PDF link']].map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div><label>Book or source title<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Pride and Prejudice, Chapter 3"/></label>{mode==='text'?<label>Source passage<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={60000} rows={7} placeholder="Paste the chapter or passage you want students to investigate…"/><small>200–60,000 characters. Paste only the reading selection for this lesson.</small></label>:mode==='file'?<label className="builder-upload"><Upload/><span>Choose a chapter or excerpt</span><input type="file" accept=".pdf,.txt,.md" onChange={e=>setFile(e.target.files?.[0]??null)}/><small>PDF up to 5 MB; TXT / Markdown up to 60,000 characters. Uploaded sources are private to the teacher; selected excerpts become student evidence.</small></label>:<label>Public PDF address<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…/chapter.pdf"/><small>Direct PDF links only. Upload files that need a login.</small></label>}<div className="builder-fields"><label>Reading range<input value={range} maxLength={200} onChange={e=>setRange(e.target.value)} placeholder="e.g. PDF pages 4–9"/><small>PDF default: first 10 pages. For text, paste the exact range.</small></label><label>Learning objective (optional)<input value={objective} maxLength={300} onChange={e=>setObjective(e.target.value)} placeholder="Let Astra propose one, or specify your own"/></label></div><div className="builder-promise"><Sparkles size={19}/><p>Astra prepares three places, three conversational characters, source cards, learning activities, a what-if scenario, and an evidence-based assessment. It selects a symbolic coast, garden, or archive setting.</p></div></>}
 {draft&&!busy&&!ready&&<div className="builder-promise"><BookOpen/><p>{draft.passages.length} passages saved from <strong>{draft.title}</strong>. Continue building from this draft without uploading again.</p></div>}
 {draft?.world&&!busy&&<><div className="builder-overview"><span className="eyebrow">{draft.world.lessonPack?.subject} · {draft.world.lessonPack?.scene} setting</span><h2>{draft.world.title}</h2><p>{draft.world.objective}</p><small>{draft.title} {draft.range&&`· ${draft.range}`}</small></div><div className="builder-places">{draft.world.nodes.map((node,i)=><article key={node.id}><span className="eyebrow">PLACE 0{i+1}</span><h3>{node.title}</h3><p>{draft.world!.lessonPack?.activities.find(a=>a.zone===node.id)?.instruction}</p><strong>Talk to {draft.world!.lessonPack?.characters.find(c=>c.zone===node.id)?.name}</strong><small>{draft.world!.lessonPack?.characters.find(c=>c.zone===node.id)?.role}</small></article>)}</div><section className="builder-sources"><h3>Check the evidence students will see</h3><p>{draft.format==='pdf'?'PDF excerpts and page references were extracted by Astra. Compare them with the original before approving.':'These excerpts retain the exact wording of your supplied text.'}</p>{draft.sourceUrl&&<p>Original PDF: <a href={draft.sourceUrl} target="_blank" rel="noreferrer">{draft.sourceUrl}</a></p>}{draft.format==='pdf'&&draft.hasUpload&&<button className="text-button" onClick={viewOriginal}>Open uploaded PDF here</button>}{original?.draftId===draft.id&&<iframe title="Original uploaded source" src={original.url}/>} {draft.world.evidence.map(e=><details key={e.id} open><summary>{e.title}</summary><blockquote>{e.text}</blockquote><small>{e.source}</small></details>)}</section><div className="builder-promise"><p><strong>What-if investigation:</strong> {draft.world.intervention}<br/>Astra’s interpretations and dialogue are generated teaching material. The scene is a symbolic setting, not a verified reconstruction of the book.</p></div><label className="builder-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I checked the excerpts, reading range, and activities for my students.</label></>}
 </div><footer>{!busy&&<button className="text-button" onClick={()=>{if(draft){setDraft(null);setReviewed(false);setOriginal(null);}else onClose();}}>{draft?'Use different material':'Keep exploring'}</button>}{ready?<button className="primary-button" disabled={!!busy||!reviewed} onClick={launch}><Check size={17}/> Launch new classroom</button>:<button className="primary-button" disabled={!!busy||(!draft&&(title.trim().length<2||(mode==='text'?text.trim().length<200:mode==='file'?!file:!url.trim())))} onClick={()=>build(draft??undefined)}><Sparkles size={17}/>{draft?'Continue building':'Build my lesson'}<ArrowRight size={17}/></button>}</footer></DialogContent></Dialog>;
}
