'use client';
import PageHeader from '@/components/PageHeader';
import {useState} from 'react';
import GeneratedWorldScene from './GeneratedWorldScene';
import WorldScene from './WorldScene';
import EvidenceReader from './EvidenceReader';
import {worldCharacters} from '@/lib/characters';
import type {World,ZoneId} from '@/lib/world';
import './world-atlas.css';
type Entry={id:string;title:string;subject:string;lessons:{id:string;world:World}[]};
export default function WorldAtlas({entries,initialLessonId}:{entries:Entry[];initialLessonId?:string}){
 const initialEntry=entries.find(e=>e.lessons.some(l=>l.id===initialLessonId))??entries[0];
 const [worldId,setWorldId]=useState(initialEntry.id),[lessonIndex,setLessonIndex]=useState(Math.max(0,initialEntry.lessons.findIndex(l=>l.id===initialLessonId))),[focus,setFocus]=useState<ZoneId|null>(null),[revision,setRevision]=useState(0),[evidenceId,setEvidenceId]=useState<string|null>(null),[guide,setGuide]=useState<ZoneId|null>(null);
 const entry=entries.find(e=>e.id===worldId)!,selected=entry.lessons[lessonIndex],world=selected.world,cast=worldCharacters(world);
 function reset(){setFocus(null);setEvidenceId(null);setGuide(null);setRevision(r=>r+1);}
 function inspect(zone:ZoneId){setFocus(zone);setRevision(r=>r+1);setGuide(null);setEvidenceId(world.evidence.find(e=>e.zone===zone)?.id??null);}
 return <main className="world-atlas"><PageHeader/><div className="atlas-heading"><span>THE WORLD LIBRARY</span><h1>Step into a text.</h1><p>Choose a world, explore its places, and read the evidence. No sign-in needed to explore.</p></div><div className="atlas-layout"><nav aria-label="Choose a world">{entries.map((e,i)=><button aria-pressed={e.id===worldId} key={e.id} onClick={()=>{setWorldId(e.id);setLessonIndex(0);reset();}}><small>{String(i+1).padStart(2,'0')} · {e.subject}</small><strong>{e.title}</strong></button>)}</nav><section className="atlas-content"><div className="atlas-lessons" role="group" aria-label="Choose a lesson">{entry.lessons.map((l,i)=><button key={l.id} aria-pressed={i===lessonIndex} onClick={()=>{setLessonIndex(i);reset();}}>Lesson {i+1}</button>)}</div><h2>{world.title}</h2><p className="atlas-question">{world.objective}</p><div className="atlas-scene">{entry.id==='alexandria'?<WorldScene world={world} scenario={false} focus={focus} focusRevision={revision} unlocked={false} hint={false} onSelect={inspect} onTalk={zone=>{setGuide(zone);setFocus(zone);setRevision(r=>r+1);}}/>:<GeneratedWorldScene world={world} scenario={false} focus={focus} focusRevision={revision} onSelect={inspect} onTalk={zone=>{setGuide(zone);setFocus(zone);setRevision(r=>r+1);}}/>}</div>{guide&&<section className="atlas-guide" aria-live="polite"><button aria-label="Close reading companion" onClick={()=>setGuide(null)}>×</button><h3>{cast[guide].name} · {cast[guide].role}</h3><p>{world.lessonPack?.activities.find(a=>a.zone===guide)?.instruction}</p><small>Prepared reading prompt. Live dialogue is available in an enabled classroom.</small></section>}<div className="atlas-stations">{world.nodes.map((node,i)=><button key={node.id} onClick={()=>inspect(node.id)}><small>STOP {i+1}</small><strong>{node.title}</strong><span>Read the assigned evidence →</span></button>)}</div><details className="atlas-reading"><summary>Reading boundary & teaching notes</summary><p>{world.lessonPack?.readingRange}</p><p>{world.lessonPack?.curriculum?.sourceNote}</p><ul>{world.lessonPack?.curriculum?.teachingNotes?.map(note=><li key={note}>{note}</li>)}</ul><a href="/curriculum-notices.txt" target="_blank" rel="noreferrer">Source editions and notices</a></details><p className="atlas-scope">Scenery and companions are interpretive teaching material. Use the cited passages as evidence. Classroom teaching includes teacher review and access setup.</p></section></div><EvidenceReader imported evidence={world.evidence.find(e=>e.id===evidenceId)??null} collected={false} student={false} busy={false} onClose={()=>setEvidenceId(null)} onCollect={async()=>{}} onUse={()=>{}}/></main>;
}
