import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {characterModels,usesForCharacter,characterSetupCode,verifyCharacterCatalog,type CharacterCatalogAsset} from '../lib/characterCatalog';
const root=new URL('../',import.meta.url);
const assets:CharacterCatalogAsset[]=characterModels.map(a=>{
 const bytes=readFileSync(new URL(`public${a.url}`,root));
 if(bytes.length!==a.bytes||createHash('sha256').update(bytes).digest('hex')!==a.sha256)throw new Error(`Stale character: ${a.id}`);
 if(bytes.readUInt32LE(0)!==0x46546c67||bytes.readUInt32LE(4)!==2||bytes.readUInt32LE(8)!==bytes.length||bytes.readUInt32LE(16)!==0x4e4f534a)throw new Error(`Invalid GLB: ${a.id}`);
 const doc=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());
 if((doc.buffers??[]).some((b:{uri?:string})=>b.uri)||(doc.images??[]).some((i:{uri?:string})=>i.uri))throw new Error(`Nonlocal character dependency: ${a.id}`);
 const triangles=(doc.meshes??[]).reduce((sum:number,m:{primitives:{indices?:number;attributes:{POSITION:number};mode?:number}[]})=>sum+m.primitives.reduce((n,p)=>{if(p.mode!==undefined&&p.mode!==4)throw new Error('Nontriangle primitive');return n+doc.accessors[p.indices??p.attributes.POSITION].count/3;},0),0);
 return {id:a.id,title:a.title,family:a.pack,creator:a.creator,sourceUrl:'/model-catalog?collection=characters',license:a.license,licenseUrl:'/models/characters/LICENSE.txt',url:a.url,bytes:a.bytes,sha256:a.sha256,dimensions:a.bounds.max.map((n,i)=>Number((n-a.bounds.min[i]).toFixed(5))),triangles,materials:(doc.materials??[]).length,skins:(doc.skins??[]).length,category:'teaching-character',classroomStatus:'authored-character',sourcePath:a.source,clips:(doc.animations??[]).map((c:{name:string})=>c.name),anchors:Object.values(a.anchors),modifications:[a.creator.includes('Quaternius')?'Original wardrobe, rig and gestures with fitted CC0 Quaternius head, eyes and hair.':'Original project-authored mesh, rig and gesture clips.','Runtime loader centers, grounds and scales each independent character instance.'],usage:{placement:'Use the assigned cast through its scene loader and existing positioned fallback groups.',cautions:a.provenance,loading:'Only the selected three readers load in a lesson; this full catalog is not an initial scene payload.',animation:'Idle, Greeting and Talk are inspectable here. The themed loader handles its own mixer and reduced motion.',rights:a.creator.includes('Quaternius')?'Original wardrobe, rig and gestures: MIT. Adapted Quaternius components: CC0 1.0. See the combined character notice.':'MIT: retain the copyright and permission notice with redistributed copies.'},assignments:usesForCharacter(a.id)};
});
verifyCharacterCatalog(assets);
writeFileSync(new URL('public/models/characters/catalog.json',root),JSON.stringify(assets,null,2)+'\n');
writeFileSync(new URL('public/models/characters/LICENSE.txt',root),readFileSync(new URL('LICENSE',root),'utf8')+'\n\nMixed-source character component notice\nRegency coat, gown and dress: head, eyes and parted hair adapted from Quaternius Universal Base Characters Kit (CC0 1.0 Universal).\nGreek companions Dorian, Thaleia and Ione: head, eyes and parted hair adapted from the same CC0 kit; Dorian also uses its fitted beard. Original gathered buns and ribbons remain project-authored.\nSource: https://quaternius.com\nLicense: https://creativecommons.org/publicdomain/zero/1.0/\nThe original wardrobe, shared rig and gesture clips remain MIT licensed. These fictional readers are not historical portraits.\n');
const lines=['# Teaching character usage guide','','Generated with `node --import tsx scripts/catalog-characters.ts` from the authored manifest and actual cast assignments. No models or manifests are modified.','',`${assets.length} independent rigged character assets serve the ten lesson worlds. The catalog at /model-catalog?collection=characters previews one at a time. A lesson loads its assigned three, not the whole collection. Clothing references inform interpretation; the fictional companions are not portraits of historical people.`,'','## Shared integration rules','','- Preserve independently loaded skeletons, the existing fallback groups, source/talk picking and scene cleanup.','- Themed scenes use `loadThemedCharacters`; Alexandria uses `loadTeachingCharacters`. Their update and readiness APIs differ.','- Preview dimensions describe source geometry. The runtime applies its own grounding/centering and character-height normalization.','- Keep the MIT copyright and permission notice when redistributing the original wardrobe and animation assets. Regency and Greek head, eye and parted-hair components, plus Dorian’s beard, are adapted from the CC0 Quaternius kit; see the combined notice.',''];
for(const a of assets){lines.push(`## ${a.title}`, '',`ID: \`${a.id}\` · ${a.bytes.toLocaleString()} bytes · ${a.triangles.toLocaleString()} triangles · ${a.materials} materials · ${a.skins} skins.`,`Source dimensions X/Y/Z: ${a.dimensions.join(' / ')} m. Clips: ${a.clips.join(', ')}.`,`Editable source: \`${a.sourcePath}\`. Anchors: ${a.anchors.join(', ')}.`,`[Runtime GLB](../public${a.url}) · [MIT notice](../public/models/characters/LICENSE.txt)`,`SHA-256: \`${a.sha256}\``, '', ...a.assignments.flatMap(u=>[`### ${u.worldLabel} · ${u.role}`,u.period,u.interpretation,`[Open lesson](http://localhost:5173/worlds?lesson=${u.worldId}-01)`,...u.references.map(r=>`- [${r.title}](${r.url})`),'','```ts',characterSetupCode(u.worldId),'```','']));}
writeFileSync(new URL('assets/CHARACTER-USAGE-GUIDE.md',root),lines.join('\n')+'\n');
console.log(JSON.stringify({characters:assets.length,sceneAssignments:assets.reduce((n,a)=>n+a.assignments.length,0),bytes:assets.reduce((n,a)=>n+a.bytes,0)},null,2));
