import {smokeTeacherHeaders} from './smoke-teacher.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.APP_URL||'http://localhost:5173';
const teacherHeaders=await smokeTeacherHeaders(base);
async function call(path,body,token,expected=200){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{...teacherHeaders,...(token?{Authorization:`Bearer ${token}`}:{ }),...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data;}
const source=`Ada believed the bridge belonged to everyone. Her neighbour Rowan argued that the builder should charge a toll because wood and labour cost money. At the town meeting, a child asked who would carry medicine across the river if the toll was too high. The council paused the vote to hear from the ferryman.\n\nThe ferryman described winter floods. He said that his boat carried travellers without charge during emergencies, but that he could not ferry everyone every day. Ada proposed a shared fund. Rowan asked who would contribute and whether poor families would be heard. Neither offered an exact budget.\n\nThe narrator records the questions without declaring a winner. At dusk, Ada and Rowan carried a broken plank back to the workshop together. The unfinished ending invites readers to consider both care for neighbours and the labour required to maintain a public bridge.`;
const c=await call('/api/classroom',{action:'create'}),other=await call('/api/classroom',{action:'create'});const endpoint=`/api/lesson-builder?id=${c.id}`;
const form=new FormData();form.set('title','The Unfinished Bridge — original classroom story');form.set('text',source);form.set('range','Complete supplied passage');form.set('objective','Compare Ada and Rowan’s perspectives using details from the passage.');
await call(endpoint,form,c.studentToken,400);let draft=await call(endpoint,form,c.teacherToken);assert.ok(draft.passages.every(p=>source.includes(p.text)));assert.equal(draft.launch,undefined);assert.equal(draft.blobKey,undefined);
await call(`/api/lesson-builder?id=${other.id}&draftId=${draft.id}`,null,other.teacherToken,403);await call(endpoint,{action:'launch',draftId:draft.id,reviewed:true},c.teacherToken,400);
assert.equal((await call(endpoint,null,c.teacherToken)).draft.id,draft.id);
console.log('PASS: text extraction, canonical excerpts, draft restore, teacher ownership and premature-launch rejection');
if(!process.argv.includes('--live'))process.exit(0);
draft=await call(endpoint,{action:'generate',draftId:draft.id},c.teacherToken);assert.ok(draft.world.lessonPack);assert.equal(draft.world.lessonPack.subject,'literature');assert.ok(draft.world.evidence.every(e=>source.includes(e.text)));await call(endpoint,{action:'launch',draftId:draft.id,reviewed:false},c.teacherToken,400);
const launch=await call(endpoint,{action:'launch',draftId:draft.id,reviewed:true},c.teacherToken),retry=await call(endpoint,{action:'launch',draftId:draft.id,reviewed:true},c.teacherToken);assert.deepEqual(launch,retry);assert.notEqual(c.id,launch.id);const snap=await call(`/api/classroom?id=${launch.id}&studentId=${launch.studentId}`,null,launch.teacherToken);assert.equal(snap.world.title,draft.world.title);assert.equal((await call(`/api/lesson-builder?id=${launch.id}`,null,launch.teacherToken)).draft.id,draft.id);
const original=await call(`/api/classroom?id=${c.id}&studentId=${c.studentId}`,null,c.teacherToken);assert.equal(original.world.lessonPack,undefined);
await mkdir('artifacts/private',{recursive:true});await writeFile('artifacts/private/builder-access.json',JSON.stringify(launch));
const talk=await call('/api/classroom',{action:'talk',id:launch.id,studentId:launch.studentId,npc:'harbor',scenario:false,requestId:crypto.randomUUID(),message:'What does the unfinished ending suggest about their disagreement?'},launch.studentToken);assert.ok(talk.turn.result.reply.length);assert.ok(!/Strabo|Alexandria|Dorian/.test(talk.turn.result.reply));console.log(`PASS: live lesson generation (${draft.run.latencyMs}ms), canonical source grounding, review gate, idempotent fresh launch, original classroom preserved, contextual character (${talk.turn.latencyMs}ms)`);
// Original one-page PDF, generated here solely to exercise multimodal file input.
const lines=source.replaceAll('\n',' ').match(/.{1,85}(?:\s|$)/g);const stream='BT /F1 11 Tf 40 760 Td '+lines.map((line,i)=>(i?'0 -18 Td ':'')+'('+line.replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)')+') Tj').join('\n')+' ET';
const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((s,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${s}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
const upload=new FormData();upload.set('title','The Unfinished Bridge PDF');upload.set('range','PDF page 1');upload.set('file',new File([pdf],'bridge.pdf',{type:'application/pdf'}));const extracted=await call(endpoint,upload,c.teacherToken);assert.equal(extracted.format,'pdf');assert.ok(extracted.passages.length>=3);assert.ok(extracted.passages.every(p=>/1/.test(p.locator)));const norm=s=>s.replace(/\s+/g,' ').trim();assert.ok(extracted.passages.every(p=>norm(source).includes(norm(p.text))));
const sourcePath=`/api/lesson-builder?id=${c.id}&draftId=${extracted.id}&source=1`;const allowed=await fetch(base+sourcePath,{headers:{Authorization:`Bearer ${c.teacherToken}`}});assert.equal(allowed.status,200);assert.equal(allowed.headers.get('Content-Type'),'application/pdf');await call(sourcePath,null,c.studentToken,403);console.log('PASS: PDF extraction and private retrieval before launch');await writeFile('artifacts/private/pdf-builder-resume.json',JSON.stringify({c,draftId:extracted.id}));const pdfReady=await call(endpoint,{action:'generate',draftId:extracted.id},c.teacherToken);const pdfLaunch=await call(endpoint,{action:'launch',draftId:pdfReady.id,reviewed:true},c.teacherToken);const retained=await fetch(base+`/api/lesson-builder?id=${pdfLaunch.id}&draftId=${extracted.id}&source=1`,{headers:{Authorization:`Bearer ${pdfLaunch.teacherToken}`}});assert.equal(retained.status,200);console.log('PASS: launched teacher retains original PDF access');console.log('PASS: real PDF extraction, excerpt fidelity, page locator, private R2 source retrieval and student denial');
