import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {portraitFingerprint} from '../lib/characterPortrait';
const base=process.env.APP_URL||'http://localhost:5173';
const {launch:c}=JSON.parse(await readFile('artifacts/private/book-image-test.json','utf8'));
const headers={Authorization:`Bearer ${c.teacherToken}`};
const snapshot=await(await fetch(`${base}/api/classroom?id=${c.id}&studentId=${c.studentId}`,{headers})).json() as any;
const npc='harbor',fingerprint=await portraitFingerprint(snapshot.world,npc);
const path=`/api/character-portrait?${new URLSearchParams({id:c.id,studentId:c.studentId,npc,fingerprint})}`;
assert.equal((await fetch(base+path)).status,403);
assert.equal((await fetch(base+path.replace(fingerprint,'wrong'),{headers})).status,403);
const generation=fetch(base+path,{method:'POST',headers}).then(r=>r.json()) as Promise<any>;
await new Promise(r=>setTimeout(r,1000));
const duplicate=await(await fetch(base+path,{method:'POST',headers})).json() as any;
assert.ok(['generating','ready'].includes(duplicate.status));console.log('PASS: authentication, stale-character rejection, concurrent generation deduplication');
const ready=await generation;assert.equal(ready.status,'ready',JSON.stringify(ready));
const cached=await(await fetch(base+path,{method:'POST',headers})).json() as any;assert.equal(cached.responseId,ready.responseId);
const teacherImage=await fetch(base+path+'&image=1',{headers});assert.equal(teacherImage.status,200);assert.equal(teacherImage.headers.get('Content-Type'),'image/png');await writeFile('artifacts/private/austen-character-portrait.png',Buffer.from(await teacherImage.arrayBuffer()));
const studentImage=await fetch(base+path+'&image=1',{headers:{Authorization:`Bearer ${c.studentToken}`}});assert.equal(studentImage.status,200);
const foreign=JSON.parse(await readFile('artifacts/private/smoke-access.json','utf8'));assert.notEqual(foreign.id,c.id);assert.equal((await fetch(base+path+'&image=1',{headers:{Authorization:`Bearer ${foreign.teacherToken}`}})).status,403);
console.log('PASS: actual Astra portrait, persistent cache, teacher and learner access, unrelated teacher denied');
