'use client';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {museumCitation,type MuseumObject} from '@/lib/museums';
import MuseumImageInspector from './MuseumImageInspector';
import './museum.css';
export function MuseumStudyContent({items}:{items:MuseumObject[]}){
 const comparing=items.length===2;
 return <><p className="museum-study-intro">{comparing?'Compare the dates and materials first, then look for similarities and differences in the images. Photographs are fitted separately; their displayed sizes do not represent the objects’ relative scale.':'Begin with what you can observe. Read the museum record before deciding what it means.'}</p><div className={`museum-study-grid ${comparing?'museum-study-pair':''}`}>{items.map(item=><article key={item.id}><span className="museum-object-kicker">{item.topic} · {item.accession}</span><h3>{item.title}</h3><MuseumImageInspector key={item.id} item={item}/><dl><dt>Date</dt><dd>{item.date}</dd><dt>Material</dt><dd>{item.medium}</dd><dt>Culture / place</dt><dd>{item.culture}</dd><dt>Dimensions</dt><dd>{item.dimensions}</dd><dt>Maker</dt><dd>{item.creator}</dd></dl><section className="museum-teaching"><span>Our discussion prompt</span><p>{item.prompt}</p><strong>What this object cannot establish</strong><p>{item.limits}</p></section><details className="museum-study-citation"><summary>Citation & credit</summary><textarea readOnly aria-label={`Citation for ${item.title}`} value={museumCitation(item)} rows={5} onFocus={event=>event.currentTarget.select()}/><p>Record retrieved {item.retrievedAt}.</p></details><a className="museum-study-record" href={item.recordUrl} target="_blank" rel="noreferrer">Original museum record ↗</a></article>)}</div>{comparing&&<section className="museum-comparison-question"><strong>What changes when you put them together?</strong><p>Name one detail they share and one difference. Do their dates, materials, or purposes change your interpretation? What additional source would help you test it?</p><small>Comparison prompt written for this app. Contextual discussion is separate from source-card assessment.</small></section>}</>;
}
export default function MuseumStudyDialog({items,onClose}:{items:MuseumObject[];onClose:()=>void}){
 return <Dialog open={items.length>0} onOpenChange={value=>{if(!value)onClose();}}><DialogContent className="museum-dialog museum-study-dialog"><DialogTitle>{items.length===2?'Two objects. A closer look.':'Look closely at the object'}</DialogTitle><DialogDescription>Museum photographs and collection records · keep observation separate from interpretation</DialogDescription><MuseumStudyContent items={items}/></DialogContent></Dialog>;
}
