'use client';
import {useState} from 'react';
import {ArrowUpRight,Check,Plus,Search} from 'lucide-react';
import {museumObjects,museumTopics,museumProviders,museumCitation,type MuseumObject} from '@/lib/museums';
import './museum.css';
import MuseumStudyDialog from './MuseumStudyDialog';
import {getMuseumInvestigation,suggestedMuseumInvestigations} from '@/lib/museumInvestigations';
import {comparisonObjects} from '@/lib/museumStudy';

function ObjectImage({item}:{item:MuseumObject}){
 const [failed,setFailed]=useState(false);
 return <div className="museum-image">{failed?<p>Photograph unavailable.<br/><a href={item.recordUrl} target="_blank" rel="noreferrer">View the museum record ↗</a></p>:<img src={item.imageUrl} alt={`Museum photograph: ${item.title}`} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>}</div>;
}
export default function MuseumCollection({selected=[],onToggle,onlySelected=false,initialTopic,onNote,initialStudy,initialObjectIds,onAddInvestigation}:{onAddInvestigation?:(id:string)=>Promise<void>;initialStudy?:string;initialObjectIds?:string[];onNote?:(id:string)=>void;initialTopic?:MuseumObject['topic'];selected?:string[];onToggle?:(id:string,included:boolean)=>Promise<void>;onlySelected?:boolean}){
 const initialPlan=onlySelected?undefined:getMuseumInvestigation(initialStudy);
 const [topic,setTopic]=useState(onlySelected?'All objects':initialTopic??initialPlan?.topic??'All objects'),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [provider,setProvider]=useState('All museums');
 const [showAllInvestigations,setShowAllInvestigations]=useState(false);
 const [compareIds,setCompareIds]=useState<string[]>([]),[studyIds,setStudyIds]=useState<string[]>(onlySelected?[]:initialPlan?.objectIds??initialObjectIds??[]);
 const studyItems=studyIds.length===2?comparisonObjects(studyIds):museumObjects.filter(item=>studyIds.includes(item.id));
 const visible=museumObjects.filter(item=>(!onlySelected||selected.includes(item.id))&&(topic==='All objects'||item.topic===topic)&&(provider==='All museums'||item.provider===provider)&&`${item.title} ${item.culture} ${item.date} ${item.medium} ${item.accession} ${item.provider} ${item.creator} ${item.topic} ${item.connection} ${item.prompt}`.toLowerCase().includes(query.toLowerCase().trim()));
 const suggested=suggestedMuseumInvestigations(onlySelected?undefined:museumTopics.find(value=>value===topic),onlySelected?selected:undefined);
 async function toggle(item:MuseumObject){if(!onToggle)return;setBusy(item.id);setError('');setNotice('');const adding=!selected.includes(item.id);try{await onToggle(item.id,adding);setNotice(`${adding?'Added to':'Removed from'} this lesson: ${item.title}`);}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.');}finally{setBusy('');}}
 async function addInvestigation(id:string){if(!onAddInvestigation)return;setBusy(id);setError('');setNotice('');try{await onAddInvestigation(id);setNotice('Both objects are now in this lesson. The discussion is available in your teaching guide and learners’ museum collection.');}catch(e){setError(e instanceof Error?e.message:'Could not add this investigation. Please retry.');}finally{setBusy('');}}
 return <div className="museum-collection">
  <p className="museum-introduction">Look closely at objects held in real museum collections. Compare what you can observe with what the museum record tells you.</p>
  <p className="museum-context">{onToggle?'Add up to six objects to this classroom. Selections are saved immediately and shared with its learners.':'Objects for observation and discussion.'} These contextual objects are separate from the source cards used for argument feedback.</p>
  {initialTopic&&!onlySelected&&<p className="museum-related">Related to this lesson: <strong>{initialTopic}</strong>. Review the date and reading limits before adding an object.</p>}
  <div role="status" className="museum-notice">{notice}</div>{error&&<p role="alert" className="museum-error">{error}</p>}
  {!!suggested.length&&<section className="museum-pathways" aria-label="Suggested investigations"><div className="museum-pathways-heading"><h2>Start with a question.</h2><p>Two objects. Eight minutes. A way into the reading.</p></div><div className="museum-pathways-grid">{(showAllInvestigations?suggested:suggested.slice(0,3)).map((plan,index)=>{const missing=plan.objectIds.filter(id=>!selected.includes(id)).length,full=selected.length+missing>6;return <article key={plan.id}><span>{String(index+1).padStart(2,'0')} / {plan.topic}</span><h3>{plan.title}</h3><p>{plan.summary}</p><div className="museum-pathway-actions"><button onClick={()=>setStudyIds([...plan.objectIds])} aria-label={`Start investigation: ${plan.title}`}>Explore this pair <ArrowUpRight size={16}/></button>{onAddInvestigation&&<><button className="museum-add-pair" disabled={!!busy||!missing||full} aria-label={`${!missing?'Already in lesson':'Add investigation'}: ${plan.title}`} onClick={()=>void addInvestigation(plan.id)}>{busy===plan.id?'Saving…':!missing?'✓ In this lesson':missing===1?'Add missing object':'Add pair to lesson'}</button>{full&&<small>Remove {selected.length+missing-6} {selected.length+missing-6===1?'object':'objects'} to make room for this pair.</small>}</>}</div></article>;})}</div>{suggested.length>3&&<button className="museum-investigations-toggle" aria-expanded={showAllInvestigations} onClick={()=>setShowAllInvestigations(value=>!value)}>{showAllInvestigations?'Show fewer investigations':`Show all ${suggested.length} investigations`}</button>}</section>}
  {!onlySelected&&<h2 className="museum-browse-heading">Browse the objects</h2>}
  {!onlySelected&&<><div className="museum-toolbar"><label className="museum-search"><Search size={16}/><span className="sr-only">Search the curated objects</span><input type="search" placeholder={`Search ${museumObjects.length} curated objects`} maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="museum-provider"><span className="sr-only">Museum collection</span><select value={provider} onChange={e=>setProvider(e.target.value)}><option>All museums</option>{museumProviders.map(value=><option key={value}>{value}</option>)}</select></label><span role="status">{visible.length} {visible.length===1?'object':'objects'}</span></div><div className="museum-filters" role="group" aria-label="Collection topic">{['All objects',...museumTopics].map(value=><button key={value} aria-pressed={topic===value} onClick={()=>setTopic(value)}>{value}</button>)}</div></>}
  {!!compareIds.length&&<aside className="museum-compare-tray" aria-label="Comparison selection"><div><strong>{compareIds.length} of 2 objects to compare</strong><p>{compareIds.map(id=>museumObjects.find(item=>item.id===id)?.title).join(' + ')}</p><small>Comparison only; this does not change the lesson’s saved objects.</small></div><button disabled={compareIds.length!==2} onClick={()=>setStudyIds([...compareIds])}>Compare objects</button><button onClick={()=>setCompareIds([])}>Clear comparison</button></aside>}
  <div className="museum-grid">{visible.map((item,index)=><article key={item.id} className="museum-object">
   <ObjectImage item={item}/><div className="museum-object-body"><div className="museum-object-kicker"><span>{item.topic}</span><span>Object {String(index+1).padStart(2,'0')}</span></div><h2>{item.title}</h2><p className="museum-date">{item.date} · {item.medium}</p><p className="museum-credit">{item.provider} · {item.accession}</p>
   <details><summary>Look closer & read the record</summary><dl><dt>Culture / place</dt><dd>{item.culture}</dd><dt>Maker</dt><dd>{item.creator}</dd><dt>Dimensions</dt><dd>{item.dimensions}</dd><dt>Credit</dt><dd>{item.credit}</dd></dl><div className="museum-teaching"><span>Discussion prompt · written for this lesson collection</span><h3>{item.connection}</h3><p>{item.prompt}</p><strong>What this object cannot establish</strong><p>{item.limits}</p></div><label className="museum-citation">Citation<textarea readOnly value={museumCitation(item)} rows={4} onFocus={event=>event.currentTarget.select()}/></label><p className="museum-record-date">Record retrieved {item.retrievedAt}. <a href={item.licenseUrl} target="_blank" rel="noreferrer">Image and metadata: CC0</a>.</p></details>
   <div className="museum-study-actions"><button aria-label={`Inspect ${item.title}`} onClick={()=>setStudyIds([item.id])}>Inspect & zoom ↗</button><button aria-label={`Compare ${item.title}`} aria-pressed={compareIds.includes(item.id)} disabled={!compareIds.includes(item.id)&&compareIds.length===2} onClick={()=>setCompareIds(ids=>ids.includes(item.id)?ids.filter(id=>id!==item.id):ids.length<2?[...ids,item.id]:ids)}>{compareIds.includes(item.id)?'✓ In comparison':'+ Compare'}</button></div>
   <div className="museum-object-actions"><a href={item.recordUrl} target="_blank" rel="noreferrer">Museum record <ArrowUpRight size={15}/></a>{onToggle&&<button disabled={!!busy||(!selected.includes(item.id)&&selected.length>=6)} aria-pressed={selected.includes(item.id)} onClick={()=>void toggle(item)}>{selected.includes(item.id)?<Check size={15}/>:<Plus size={15}/>} {busy===item.id?'Saving…':selected.includes(item.id)?'Remove from lesson':'Add to lesson'}</button>}</div>
  </div></article>)}</div>
  {!visible.length&&<div className="museum-empty"><p>{onlySelected?'Your teacher has not added museum objects to this lesson yet.':'No objects match these filters.'}</p>{!onlySelected&&<button onClick={()=>{setQuery('');setTopic('All objects');setProvider('All museums');}}>Show all objects</button>}</div>}
  <MuseumStudyDialog onNote={onNote} key={studyIds.join('-')} items={studyItems} onClose={()=>setStudyIds([])}/>
  <p className="museum-endnote">A reviewed collection of {museumObjects.length} objects from {museumProviders.length} museums, using open-access records from Cleveland and The Met. Museum photographs are distinct from the app’s generated settings. No museum partnership is implied.</p>
 </div>;
}
